// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZSvxJYzL_UsuYzpsNXUqp41DQ0Vrv0TE',
    appId: '1:128726424198:web:fc25fcfc80bd5ee10d4f07',
    messagingSenderId: '128726424198',
    projectId: 'diet-planner-af821',
    authDomain: 'diet-planner-af821.firebaseapp.com',
    storageBucket: 'diet-planner-af821.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeOzKPqgVLUomk4OY717CLi2SSarx1Z-o',
    appId: '1:128726424198:android:6a7d2b96b08336690d4f07',
    messagingSenderId: '128726424198',
    projectId: 'diet-planner-af821',
    storageBucket: 'diet-planner-af821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBifZ9zFX16J2swq1msG1OfO6w-_3Z1nTg',
    appId: '1:128726424198:ios:0a35877823ec70470d4f07',
    messagingSenderId: '128726424198',
    projectId: 'diet-planner-af821',
    storageBucket: 'diet-planner-af821.firebasestorage.app',
    iosBundleId: 'com.example.dietPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBifZ9zFX16J2swq1msG1OfO6w-_3Z1nTg',
    appId: '1:128726424198:ios:0a35877823ec70470d4f07',
    messagingSenderId: '128726424198',
    projectId: 'diet-planner-af821',
    storageBucket: 'diet-planner-af821.firebasestorage.app',
    iosBundleId: 'com.example.dietPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZSvxJYzL_UsuYzpsNXUqp41DQ0Vrv0TE',
    appId: '1:128726424198:web:fa8ee9c1455eb8a70d4f07',
    messagingSenderId: '128726424198',
    projectId: 'diet-planner-af821',
    authDomain: 'diet-planner-af821.firebaseapp.com',
    storageBucket: 'diet-planner-af821.firebasestorage.app',
  );
}